version: '2'
services:
  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    environment:
     - COMPOSE_CONVERT_WINDOWS_PATHS=1
     - CASSANDRA_BROADCAST_ADDRESS=cassandra
    ports:
     - "9042:9042"
     - 9160
     - 7000
     - 7001
     - 7199
    volumes:
     - /var/lib/cassandra 
     
  